// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cache.proto

package com.orosoft.grpc;

public interface GetLoginAttemptsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetLoginAttemptsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 login_attempts = 1;</code>
   */
  int getLoginAttempts();
}
