// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cache.proto

package com.orosoft.grpc;

/**
 * Protobuf type {@code GetLoginAttemptsResponse}
 */
public  final class GetLoginAttemptsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetLoginAttemptsResponse)
    GetLoginAttemptsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetLoginAttemptsResponse.newBuilder() to construct.
  private GetLoginAttemptsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetLoginAttemptsResponse() {
    loginAttempts_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetLoginAttemptsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            loginAttempts_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.orosoft.grpc.Cache.internal_static_GetLoginAttemptsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.orosoft.grpc.Cache.internal_static_GetLoginAttemptsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.orosoft.grpc.GetLoginAttemptsResponse.class, com.orosoft.grpc.GetLoginAttemptsResponse.Builder.class);
  }

  public static final int LOGIN_ATTEMPTS_FIELD_NUMBER = 1;
  private int loginAttempts_;
  /**
   * <code>int32 login_attempts = 1;</code>
   */
  public int getLoginAttempts() {
    return loginAttempts_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (loginAttempts_ != 0) {
      output.writeInt32(1, loginAttempts_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (loginAttempts_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, loginAttempts_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.orosoft.grpc.GetLoginAttemptsResponse)) {
      return super.equals(obj);
    }
    com.orosoft.grpc.GetLoginAttemptsResponse other = (com.orosoft.grpc.GetLoginAttemptsResponse) obj;

    boolean result = true;
    result = result && (getLoginAttempts()
        == other.getLoginAttempts());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LOGIN_ATTEMPTS_FIELD_NUMBER;
    hash = (53 * hash) + getLoginAttempts();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.orosoft.grpc.GetLoginAttemptsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.orosoft.grpc.GetLoginAttemptsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.orosoft.grpc.GetLoginAttemptsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.orosoft.grpc.GetLoginAttemptsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.orosoft.grpc.GetLoginAttemptsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.orosoft.grpc.GetLoginAttemptsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.orosoft.grpc.GetLoginAttemptsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.orosoft.grpc.GetLoginAttemptsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.orosoft.grpc.GetLoginAttemptsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.orosoft.grpc.GetLoginAttemptsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.orosoft.grpc.GetLoginAttemptsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.orosoft.grpc.GetLoginAttemptsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.orosoft.grpc.GetLoginAttemptsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetLoginAttemptsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetLoginAttemptsResponse)
      com.orosoft.grpc.GetLoginAttemptsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.orosoft.grpc.Cache.internal_static_GetLoginAttemptsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.orosoft.grpc.Cache.internal_static_GetLoginAttemptsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.orosoft.grpc.GetLoginAttemptsResponse.class, com.orosoft.grpc.GetLoginAttemptsResponse.Builder.class);
    }

    // Construct using com.orosoft.grpc.GetLoginAttemptsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      loginAttempts_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.orosoft.grpc.Cache.internal_static_GetLoginAttemptsResponse_descriptor;
    }

    @java.lang.Override
    public com.orosoft.grpc.GetLoginAttemptsResponse getDefaultInstanceForType() {
      return com.orosoft.grpc.GetLoginAttemptsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.orosoft.grpc.GetLoginAttemptsResponse build() {
      com.orosoft.grpc.GetLoginAttemptsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.orosoft.grpc.GetLoginAttemptsResponse buildPartial() {
      com.orosoft.grpc.GetLoginAttemptsResponse result = new com.orosoft.grpc.GetLoginAttemptsResponse(this);
      result.loginAttempts_ = loginAttempts_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.orosoft.grpc.GetLoginAttemptsResponse) {
        return mergeFrom((com.orosoft.grpc.GetLoginAttemptsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.orosoft.grpc.GetLoginAttemptsResponse other) {
      if (other == com.orosoft.grpc.GetLoginAttemptsResponse.getDefaultInstance()) return this;
      if (other.getLoginAttempts() != 0) {
        setLoginAttempts(other.getLoginAttempts());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.orosoft.grpc.GetLoginAttemptsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.orosoft.grpc.GetLoginAttemptsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int loginAttempts_ ;
    /**
     * <code>int32 login_attempts = 1;</code>
     */
    public int getLoginAttempts() {
      return loginAttempts_;
    }
    /**
     * <code>int32 login_attempts = 1;</code>
     */
    public Builder setLoginAttempts(int value) {
      
      loginAttempts_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 login_attempts = 1;</code>
     */
    public Builder clearLoginAttempts() {
      
      loginAttempts_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetLoginAttemptsResponse)
  }

  // @@protoc_insertion_point(class_scope:GetLoginAttemptsResponse)
  private static final com.orosoft.grpc.GetLoginAttemptsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.orosoft.grpc.GetLoginAttemptsResponse();
  }

  public static com.orosoft.grpc.GetLoginAttemptsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetLoginAttemptsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetLoginAttemptsResponse>() {
    @java.lang.Override
    public GetLoginAttemptsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetLoginAttemptsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetLoginAttemptsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetLoginAttemptsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.orosoft.grpc.GetLoginAttemptsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

