// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cache.proto

package com.orosoft.grpc;

/**
 * Protobuf type {@code ValidateOTPResponse}
 */
public  final class ValidateOTPResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ValidateOTPResponse)
    ValidateOTPResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ValidateOTPResponse.newBuilder() to construct.
  private ValidateOTPResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ValidateOTPResponse() {
    optMatched_ = false;
    maxTryReach_ = false;
    userIdValid_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ValidateOTPResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            optMatched_ = input.readBool();
            break;
          }
          case 16: {

            maxTryReach_ = input.readBool();
            break;
          }
          case 24: {

            userIdValid_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.orosoft.grpc.Cache.internal_static_ValidateOTPResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.orosoft.grpc.Cache.internal_static_ValidateOTPResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.orosoft.grpc.ValidateOTPResponse.class, com.orosoft.grpc.ValidateOTPResponse.Builder.class);
  }

  public static final int OPTMATCHED_FIELD_NUMBER = 1;
  private boolean optMatched_;
  /**
   * <code>bool optMatched = 1;</code>
   */
  public boolean getOptMatched() {
    return optMatched_;
  }

  public static final int MAXTRYREACH_FIELD_NUMBER = 2;
  private boolean maxTryReach_;
  /**
   * <code>bool MaxTryReach = 2;</code>
   */
  public boolean getMaxTryReach() {
    return maxTryReach_;
  }

  public static final int USERIDVALID_FIELD_NUMBER = 3;
  private boolean userIdValid_;
  /**
   * <code>bool userIdValid = 3;</code>
   */
  public boolean getUserIdValid() {
    return userIdValid_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (optMatched_ != false) {
      output.writeBool(1, optMatched_);
    }
    if (maxTryReach_ != false) {
      output.writeBool(2, maxTryReach_);
    }
    if (userIdValid_ != false) {
      output.writeBool(3, userIdValid_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (optMatched_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, optMatched_);
    }
    if (maxTryReach_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, maxTryReach_);
    }
    if (userIdValid_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, userIdValid_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.orosoft.grpc.ValidateOTPResponse)) {
      return super.equals(obj);
    }
    com.orosoft.grpc.ValidateOTPResponse other = (com.orosoft.grpc.ValidateOTPResponse) obj;

    boolean result = true;
    result = result && (getOptMatched()
        == other.getOptMatched());
    result = result && (getMaxTryReach()
        == other.getMaxTryReach());
    result = result && (getUserIdValid()
        == other.getUserIdValid());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OPTMATCHED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getOptMatched());
    hash = (37 * hash) + MAXTRYREACH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getMaxTryReach());
    hash = (37 * hash) + USERIDVALID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getUserIdValid());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.orosoft.grpc.ValidateOTPResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.orosoft.grpc.ValidateOTPResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.orosoft.grpc.ValidateOTPResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.orosoft.grpc.ValidateOTPResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.orosoft.grpc.ValidateOTPResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.orosoft.grpc.ValidateOTPResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.orosoft.grpc.ValidateOTPResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.orosoft.grpc.ValidateOTPResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.orosoft.grpc.ValidateOTPResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.orosoft.grpc.ValidateOTPResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.orosoft.grpc.ValidateOTPResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.orosoft.grpc.ValidateOTPResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.orosoft.grpc.ValidateOTPResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ValidateOTPResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ValidateOTPResponse)
      com.orosoft.grpc.ValidateOTPResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.orosoft.grpc.Cache.internal_static_ValidateOTPResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.orosoft.grpc.Cache.internal_static_ValidateOTPResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.orosoft.grpc.ValidateOTPResponse.class, com.orosoft.grpc.ValidateOTPResponse.Builder.class);
    }

    // Construct using com.orosoft.grpc.ValidateOTPResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      optMatched_ = false;

      maxTryReach_ = false;

      userIdValid_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.orosoft.grpc.Cache.internal_static_ValidateOTPResponse_descriptor;
    }

    @java.lang.Override
    public com.orosoft.grpc.ValidateOTPResponse getDefaultInstanceForType() {
      return com.orosoft.grpc.ValidateOTPResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.orosoft.grpc.ValidateOTPResponse build() {
      com.orosoft.grpc.ValidateOTPResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.orosoft.grpc.ValidateOTPResponse buildPartial() {
      com.orosoft.grpc.ValidateOTPResponse result = new com.orosoft.grpc.ValidateOTPResponse(this);
      result.optMatched_ = optMatched_;
      result.maxTryReach_ = maxTryReach_;
      result.userIdValid_ = userIdValid_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.orosoft.grpc.ValidateOTPResponse) {
        return mergeFrom((com.orosoft.grpc.ValidateOTPResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.orosoft.grpc.ValidateOTPResponse other) {
      if (other == com.orosoft.grpc.ValidateOTPResponse.getDefaultInstance()) return this;
      if (other.getOptMatched() != false) {
        setOptMatched(other.getOptMatched());
      }
      if (other.getMaxTryReach() != false) {
        setMaxTryReach(other.getMaxTryReach());
      }
      if (other.getUserIdValid() != false) {
        setUserIdValid(other.getUserIdValid());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.orosoft.grpc.ValidateOTPResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.orosoft.grpc.ValidateOTPResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean optMatched_ ;
    /**
     * <code>bool optMatched = 1;</code>
     */
    public boolean getOptMatched() {
      return optMatched_;
    }
    /**
     * <code>bool optMatched = 1;</code>
     */
    public Builder setOptMatched(boolean value) {
      
      optMatched_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool optMatched = 1;</code>
     */
    public Builder clearOptMatched() {
      
      optMatched_ = false;
      onChanged();
      return this;
    }

    private boolean maxTryReach_ ;
    /**
     * <code>bool MaxTryReach = 2;</code>
     */
    public boolean getMaxTryReach() {
      return maxTryReach_;
    }
    /**
     * <code>bool MaxTryReach = 2;</code>
     */
    public Builder setMaxTryReach(boolean value) {
      
      maxTryReach_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool MaxTryReach = 2;</code>
     */
    public Builder clearMaxTryReach() {
      
      maxTryReach_ = false;
      onChanged();
      return this;
    }

    private boolean userIdValid_ ;
    /**
     * <code>bool userIdValid = 3;</code>
     */
    public boolean getUserIdValid() {
      return userIdValid_;
    }
    /**
     * <code>bool userIdValid = 3;</code>
     */
    public Builder setUserIdValid(boolean value) {
      
      userIdValid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool userIdValid = 3;</code>
     */
    public Builder clearUserIdValid() {
      
      userIdValid_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ValidateOTPResponse)
  }

  // @@protoc_insertion_point(class_scope:ValidateOTPResponse)
  private static final com.orosoft.grpc.ValidateOTPResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.orosoft.grpc.ValidateOTPResponse();
  }

  public static com.orosoft.grpc.ValidateOTPResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ValidateOTPResponse>
      PARSER = new com.google.protobuf.AbstractParser<ValidateOTPResponse>() {
    @java.lang.Override
    public ValidateOTPResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ValidateOTPResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ValidateOTPResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ValidateOTPResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.orosoft.grpc.ValidateOTPResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

