// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cache.proto

package com.orosoft.grpc;

public final class Cache {
  private Cache() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StoreUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StoreUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RemoveUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RemoveUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RemoveUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RemoveUserResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013cache.proto\"\035\n\013UserRequest\022\016\n\006userId\030\001" +
      " \001(\t\"g\n\010UserData\022\016\n\006userId\030\001 \001(\t\022\014\n\004name" +
      "\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\022\017\n\007contact\030\004 \001(\t\022\013" +
      "\n\003dob\030\005 \001(\t\022\020\n\010password\030\006 \001(\t\"$\n\021StoreUs" +
      "erResponse\022\017\n\007success\030\001 \001(\010\"#\n\021RemoveUse" +
      "rRequest\022\016\n\006userId\030\001 \001(\t\"%\n\022RemoveUserRe" +
      "sponse\022\017\n\007success\030\001 \001(\0102\227\001\n\016CachingServi" +
      "ce\022\"\n\007getUser\022\014.UserRequest\032\t.UserData\022*" +
      "\n\tstoreUser\022\t.UserData\032\022.StoreUserRespon" +
      "se\0225\n\nremoveUser\022\022.RemoveUserRequest\032\023.R" +
      "emoveUserResponseB\024\n\020com.orosoft.grpcP\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_UserRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_UserData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UserData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserData_descriptor,
        new java.lang.String[] { "UserId", "Name", "Email", "Contact", "Dob", "Password", });
    internal_static_StoreUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_StoreUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StoreUserResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_RemoveUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_RemoveUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RemoveUserRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_RemoveUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_RemoveUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RemoveUserResponse_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
