// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: History.proto

package com.orosoft.grpc.history;

public interface ProductsHistoryDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductsHistoryData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string productId = 2;</code>
   */
  java.lang.String getProductId();
  /**
   * <code>string productId = 2;</code>
   */
  com.google.protobuf.ByteString
      getProductIdBytes();

  /**
   * <code>string categoryId = 3;</code>
   */
  java.lang.String getCategoryId();
  /**
   * <code>string categoryId = 3;</code>
   */
  com.google.protobuf.ByteString
      getCategoryIdBytes();

  /**
   * <code>string imagePath = 4;</code>
   */
  java.lang.String getImagePath();
  /**
   * <code>string imagePath = 4;</code>
   */
  com.google.protobuf.ByteString
      getImagePathBytes();

  /**
   * <code>string productionDescription = 5;</code>
   */
  java.lang.String getProductionDescription();
  /**
   * <code>string productionDescription = 5;</code>
   */
  com.google.protobuf.ByteString
      getProductionDescriptionBytes();

  /**
   * <code>string productName = 6;</code>
   */
  java.lang.String getProductName();
  /**
   * <code>string productName = 6;</code>
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>string productPrice = 7;</code>
   */
  java.lang.String getProductPrice();
  /**
   * <code>string productPrice = 7;</code>
   */
  com.google.protobuf.ByteString
      getProductPriceBytes();

  /**
   * <code>int32 viewCount = 8;</code>
   */
  int getViewCount();
}
