// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: History.proto

package com.orosoft.grpc.history;

public interface StoreCategoriesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StoreCategoriesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();
}
