// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: History.proto

package com.orosoft.grpc.history;

public interface CategoriesHistoryDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CategoriesHistoryData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string categoryId = 2;</code>
   */
  java.lang.String getCategoryId();
  /**
   * <code>string categoryId = 2;</code>
   */
  com.google.protobuf.ByteString
      getCategoryIdBytes();

  /**
   * <code>string categoryName = 3;</code>
   */
  java.lang.String getCategoryName();
  /**
   * <code>string categoryName = 3;</code>
   */
  com.google.protobuf.ByteString
      getCategoryNameBytes();

  /**
   * <code>string imagePath = 4;</code>
   */
  java.lang.String getImagePath();
  /**
   * <code>string imagePath = 4;</code>
   */
  com.google.protobuf.ByteString
      getImagePathBytes();
}
