// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: History.proto

package com.orosoft.grpc.history;

/**
 * Protobuf type {@code CategoriesHistoryData}
 */
public  final class CategoriesHistoryData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CategoriesHistoryData)
    CategoriesHistoryDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CategoriesHistoryData.newBuilder() to construct.
  private CategoriesHistoryData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CategoriesHistoryData() {
    userId_ = "";
    categoryId_ = "";
    categoryName_ = "";
    imagePath_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CategoriesHistoryData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            userId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            categoryId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            categoryName_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            imagePath_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.orosoft.grpc.history.History.internal_static_CategoriesHistoryData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.orosoft.grpc.history.History.internal_static_CategoriesHistoryData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.orosoft.grpc.history.CategoriesHistoryData.class, com.orosoft.grpc.history.CategoriesHistoryData.Builder.class);
  }

  public static final int USERID_FIELD_NUMBER = 1;
  private volatile java.lang.Object userId_;
  /**
   * <code>string userId = 1;</code>
   */
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <code>string userId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CATEGORYID_FIELD_NUMBER = 2;
  private volatile java.lang.Object categoryId_;
  /**
   * <code>string categoryId = 2;</code>
   */
  public java.lang.String getCategoryId() {
    java.lang.Object ref = categoryId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      categoryId_ = s;
      return s;
    }
  }
  /**
   * <code>string categoryId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCategoryIdBytes() {
    java.lang.Object ref = categoryId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      categoryId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CATEGORYNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object categoryName_;
  /**
   * <code>string categoryName = 3;</code>
   */
  public java.lang.String getCategoryName() {
    java.lang.Object ref = categoryName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      categoryName_ = s;
      return s;
    }
  }
  /**
   * <code>string categoryName = 3;</code>
   */
  public com.google.protobuf.ByteString
      getCategoryNameBytes() {
    java.lang.Object ref = categoryName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      categoryName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMAGEPATH_FIELD_NUMBER = 4;
  private volatile java.lang.Object imagePath_;
  /**
   * <code>string imagePath = 4;</code>
   */
  public java.lang.String getImagePath() {
    java.lang.Object ref = imagePath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      imagePath_ = s;
      return s;
    }
  }
  /**
   * <code>string imagePath = 4;</code>
   */
  public com.google.protobuf.ByteString
      getImagePathBytes() {
    java.lang.Object ref = imagePath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      imagePath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getUserIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
    }
    if (!getCategoryIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, categoryId_);
    }
    if (!getCategoryNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, categoryName_);
    }
    if (!getImagePathBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, imagePath_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getUserIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
    }
    if (!getCategoryIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, categoryId_);
    }
    if (!getCategoryNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, categoryName_);
    }
    if (!getImagePathBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, imagePath_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.orosoft.grpc.history.CategoriesHistoryData)) {
      return super.equals(obj);
    }
    com.orosoft.grpc.history.CategoriesHistoryData other = (com.orosoft.grpc.history.CategoriesHistoryData) obj;

    boolean result = true;
    result = result && getUserId()
        .equals(other.getUserId());
    result = result && getCategoryId()
        .equals(other.getCategoryId());
    result = result && getCategoryName()
        .equals(other.getCategoryName());
    result = result && getImagePath()
        .equals(other.getImagePath());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    hash = (37 * hash) + CATEGORYID_FIELD_NUMBER;
    hash = (53 * hash) + getCategoryId().hashCode();
    hash = (37 * hash) + CATEGORYNAME_FIELD_NUMBER;
    hash = (53 * hash) + getCategoryName().hashCode();
    hash = (37 * hash) + IMAGEPATH_FIELD_NUMBER;
    hash = (53 * hash) + getImagePath().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.orosoft.grpc.history.CategoriesHistoryData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.orosoft.grpc.history.CategoriesHistoryData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.orosoft.grpc.history.CategoriesHistoryData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.orosoft.grpc.history.CategoriesHistoryData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.orosoft.grpc.history.CategoriesHistoryData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.orosoft.grpc.history.CategoriesHistoryData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.orosoft.grpc.history.CategoriesHistoryData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.orosoft.grpc.history.CategoriesHistoryData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.orosoft.grpc.history.CategoriesHistoryData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.orosoft.grpc.history.CategoriesHistoryData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.orosoft.grpc.history.CategoriesHistoryData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.orosoft.grpc.history.CategoriesHistoryData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.orosoft.grpc.history.CategoriesHistoryData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CategoriesHistoryData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CategoriesHistoryData)
      com.orosoft.grpc.history.CategoriesHistoryDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.orosoft.grpc.history.History.internal_static_CategoriesHistoryData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.orosoft.grpc.history.History.internal_static_CategoriesHistoryData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.orosoft.grpc.history.CategoriesHistoryData.class, com.orosoft.grpc.history.CategoriesHistoryData.Builder.class);
    }

    // Construct using com.orosoft.grpc.history.CategoriesHistoryData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      userId_ = "";

      categoryId_ = "";

      categoryName_ = "";

      imagePath_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.orosoft.grpc.history.History.internal_static_CategoriesHistoryData_descriptor;
    }

    @java.lang.Override
    public com.orosoft.grpc.history.CategoriesHistoryData getDefaultInstanceForType() {
      return com.orosoft.grpc.history.CategoriesHistoryData.getDefaultInstance();
    }

    @java.lang.Override
    public com.orosoft.grpc.history.CategoriesHistoryData build() {
      com.orosoft.grpc.history.CategoriesHistoryData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.orosoft.grpc.history.CategoriesHistoryData buildPartial() {
      com.orosoft.grpc.history.CategoriesHistoryData result = new com.orosoft.grpc.history.CategoriesHistoryData(this);
      result.userId_ = userId_;
      result.categoryId_ = categoryId_;
      result.categoryName_ = categoryName_;
      result.imagePath_ = imagePath_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.orosoft.grpc.history.CategoriesHistoryData) {
        return mergeFrom((com.orosoft.grpc.history.CategoriesHistoryData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.orosoft.grpc.history.CategoriesHistoryData other) {
      if (other == com.orosoft.grpc.history.CategoriesHistoryData.getDefaultInstance()) return this;
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        onChanged();
      }
      if (!other.getCategoryId().isEmpty()) {
        categoryId_ = other.categoryId_;
        onChanged();
      }
      if (!other.getCategoryName().isEmpty()) {
        categoryName_ = other.categoryName_;
        onChanged();
      }
      if (!other.getImagePath().isEmpty()) {
        imagePath_ = other.imagePath_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.orosoft.grpc.history.CategoriesHistoryData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.orosoft.grpc.history.CategoriesHistoryData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object userId_ = "";
    /**
     * <code>string userId = 1;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userId = 1;</code>
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userId = 1;</code>
     */
    public Builder clearUserId() {
      
      userId_ = getDefaultInstance().getUserId();
      onChanged();
      return this;
    }
    /**
     * <code>string userId = 1;</code>
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object categoryId_ = "";
    /**
     * <code>string categoryId = 2;</code>
     */
    public java.lang.String getCategoryId() {
      java.lang.Object ref = categoryId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        categoryId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string categoryId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCategoryIdBytes() {
      java.lang.Object ref = categoryId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        categoryId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string categoryId = 2;</code>
     */
    public Builder setCategoryId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      categoryId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string categoryId = 2;</code>
     */
    public Builder clearCategoryId() {
      
      categoryId_ = getDefaultInstance().getCategoryId();
      onChanged();
      return this;
    }
    /**
     * <code>string categoryId = 2;</code>
     */
    public Builder setCategoryIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      categoryId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object categoryName_ = "";
    /**
     * <code>string categoryName = 3;</code>
     */
    public java.lang.String getCategoryName() {
      java.lang.Object ref = categoryName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        categoryName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string categoryName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCategoryNameBytes() {
      java.lang.Object ref = categoryName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        categoryName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string categoryName = 3;</code>
     */
    public Builder setCategoryName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      categoryName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string categoryName = 3;</code>
     */
    public Builder clearCategoryName() {
      
      categoryName_ = getDefaultInstance().getCategoryName();
      onChanged();
      return this;
    }
    /**
     * <code>string categoryName = 3;</code>
     */
    public Builder setCategoryNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      categoryName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object imagePath_ = "";
    /**
     * <code>string imagePath = 4;</code>
     */
    public java.lang.String getImagePath() {
      java.lang.Object ref = imagePath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imagePath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string imagePath = 4;</code>
     */
    public com.google.protobuf.ByteString
        getImagePathBytes() {
      java.lang.Object ref = imagePath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imagePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string imagePath = 4;</code>
     */
    public Builder setImagePath(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      imagePath_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string imagePath = 4;</code>
     */
    public Builder clearImagePath() {
      
      imagePath_ = getDefaultInstance().getImagePath();
      onChanged();
      return this;
    }
    /**
     * <code>string imagePath = 4;</code>
     */
    public Builder setImagePathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      imagePath_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CategoriesHistoryData)
  }

  // @@protoc_insertion_point(class_scope:CategoriesHistoryData)
  private static final com.orosoft.grpc.history.CategoriesHistoryData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.orosoft.grpc.history.CategoriesHistoryData();
  }

  public static com.orosoft.grpc.history.CategoriesHistoryData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CategoriesHistoryData>
      PARSER = new com.google.protobuf.AbstractParser<CategoriesHistoryData>() {
    @java.lang.Override
    public CategoriesHistoryData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CategoriesHistoryData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CategoriesHistoryData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CategoriesHistoryData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.orosoft.grpc.history.CategoriesHistoryData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

