// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: History.proto

package com.orosoft.grpc.history;

public interface RemoveProductsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RemoveProductsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();
}
