// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cache.proto

package com.orosoft.grpc;

public interface StoreOTPOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StoreOTP)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string OTP = 2;</code>
   */
  java.lang.String getOTP();
  /**
   * <code>string OTP = 2;</code>
   */
  com.google.protobuf.ByteString
      getOTPBytes();
}
