// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cache.proto

package com.orosoft.grpc;

public interface UserSessionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserSession)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>int32 sessionId = 2;</code>
   */
  int getSessionId();

  /**
   * <code>string token = 3;</code>
   */
  java.lang.String getToken();
  /**
   * <code>string token = 3;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>string deviceString = 4;</code>
   */
  java.lang.String getDeviceString();
  /**
   * <code>string deviceString = 4;</code>
   */
  com.google.protobuf.ByteString
      getDeviceStringBytes();
}
