// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cache.proto

package com.orosoft.grpc;

public interface UserDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string email = 3;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 3;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string contact = 4;</code>
   */
  java.lang.String getContact();
  /**
   * <code>string contact = 4;</code>
   */
  com.google.protobuf.ByteString
      getContactBytes();

  /**
   * <code>string dob = 5;</code>
   */
  java.lang.String getDob();
  /**
   * <code>string dob = 5;</code>
   */
  com.google.protobuf.ByteString
      getDobBytes();

  /**
   * <code>string password = 6;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 6;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
