// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cache.proto

package com.orosoft.grpc;

public interface ValidateOTPRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ValidateOTPRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string otp = 2;</code>
   */
  java.lang.String getOtp();
  /**
   * <code>string otp = 2;</code>
   */
  com.google.protobuf.ByteString
      getOtpBytes();

  /**
   * <code>int32 maxTry = 3;</code>
   */
  int getMaxTry();
}
